openapi: 3.0.1
info:
  title: JenkingAPI
  description: API Definition of JenkingAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/japi
paths:
  /:
    get:
      responses:
        default:
          description: Default response
